### PR TITLE
Stream and visualize human effort data in HumanStateVisualizer

### PR DESCRIPTION
**Pull request by dariosortino**
As per title, this PR:
- Allows the stream and the visualization of human effort data by the color of spheres object
- Allows to set the maxEffort in the `.ini` file for each joint to which the associated sphere saturates in red
- Allows to set a background color from the `.ini` file

This PR depends by https://github.com/robotology/idyntree/pull/1163

@S-Dafarra

### CODE REVIEW

**Comment by S-Dafarra** [comment]
I think it is worth specifying that you need version 11.1.0 of ``iDynTree`` in https://github.com/robotology/human-dynamics-estimation/blob/cdf9c94238200ed30a348cbabe45b528ec0f7e72/modules/HumanStateVisualizer/CMakeLists.txt#L18 otherwise it will fail to compile

**Comment by S-Dafarra** [comment]
> I think it is worth specifying that you need version 11.1.0 of `iDynTree` in
> 
> https://github.com/robotology/human-dynamics-estimation/blob/cdf9c94238200ed30a348cbabe45b528ec0f7e72/modules/HumanStateVisualizer/CMakeLists.txt#L18
> 
> otherwise it will fail to compile

Actually, 12.0.0 after https://github.com/robotology/idyntree/pull/1163/commits/f5c4bd60cc1a3a9746ef2af7a6bf38f088a580f3 😅

**Comment by dariosortino** [comment]
@traversaro the checks failed because there were no iDynTree 12.0.0 version upstream, but now that you merged [this](https://github.com/robotology/idyntree/pull/1163) it should work. How can we trigger the checks again?

**Comment by S-Dafarra** [comment]
> @traversaro the checks failed because there were no iDynTree 12.0.0 version upstream, but now that you merged [this](https://github.com/robotology/idyntree/pull/1163) it should work. How can we trigger the checks again?

You can rerun failed jobs here: 
image

**Comment by S-Dafarra** [comment]
Actually, this line needs to be edited https://github.com/robotology/human-dynamics-estimation/blob/cdf9c94238200ed30a348cbabe45b528ec0f7e72/.github/workflows/ci.yml#L18

**Comment by S-Dafarra** [comment]
In Windows and MacOS it will fail until ``idyntree`` gets updated in ``conda``. See https://github.com/conda-forge/idyntree-feedstock/pull/81

**Comment by dariosortino** [comment]
I was suspecting something related to conda packages not being updated yet.

> You can rerun failed jobs here: image

By the way, I think I don't have the permissions to re-run jobs because I can't see that button

**Comment by traversaro** [comment]
> By the way, I think I don't have the permissions to re-run jobs because I can't see that button

We can look into fixing this, but just FYI a common workaround is just to close and reopen the PR.

**Comment by traversaro** [comment]
You should have permissions now, and iDynTree 12.0.0 should have been released in conda-forge.

**Comment by traversaro** [comment]
Unfortunately here we also install wearables, that still required iDynTree 11. We can switch to build wearables from source, etherwise I guess it could take some days to get wearables compiled with idyntree 12 .

**Comment by dariosortino** [comment]
@traversaro it's up to you, I don't know the details about the different options

**Pull request merged**
