### PR TITLE
Increase the range of motion of the icub3 elbow joints in the urdf model 

### PR DESCRIPTION
**Pull request by kouroshD**
Following this issue: https://github.com/ami-iit/component_ANA-Avatar-XPRIZE/issues/411

This PR has to be rebased after the merge of the PR https://github.com/robotology/human-dynamics-estimation/pull/270 .

### CODE REVIEW

**Comment by lrapetti** [comment]
> This PR has to be rebased after the merge of the PR #270 .

PR merged!

**Review by lrapetti — APPROVED** [review]
Changes looks good, you just need to clan the commit history after #270!

**Comment by kouroshD** [comment]
> Changes looks good, you just need to clan the commit history after #270!

done!

**Comment by lrapetti** [comment]
Great! Feel free to merge if no other changes are needed

**Comment by kouroshD** [comment]
> Great! Feel free to merge if no other changes are needed

I have added the custom constraints for all the icub3 configuration files, according to https://github.com/ami-iit/component_ifeel/commit/fc52c3b7bafdc65bc78708557c7d8b0579b76b2f.
Feel free to have another look @lrapetti  and merge. Thanks

**Comment by lrapetti** [comment]
Thanks @kouroshD, we can merge!

**Pull request merged**
