### PR TITLE
Fix Travis CI

### PR DESCRIPTION
**Pull request by lrapetti**
Cherry pick of the commit fixing Travis CI in `devel` (https://github.com/robotology/human-dynamics-estimation/pull/125)

### CODE REVIEW

**Comment by lrapetti** [comment]
The check failed because it was pointing to a branch of wearable that no longer exists, while it was already fixed in the `devel` branch (https://github.com/robotology/human-dynamics-estimation/blob/devel/.ci/build_deps.sh#L71). I will add the change also here in the master.

**Comment by traversaro** [comment]
We can also simply merge `devel` in `master` if it is simpler. I do not think anyone is using the `master` branch of the repo.

**Comment by lrapetti** [comment]
> We can also simply merge `devel` in `master` if it is simpler. I do not think anyone is using the `master` branch of the repo.

I agree on that, @kouroshD @Yeshasvitvs what do you think?

**Comment by kouroshD** [comment]
> > We can also simply merge `devel` in `master` if it is simpler. I do not think anyone is using the `master` branch of the repo.
> 
> I agree on that, @kouroshD @Yeshasvitvs what do you think?

To me is completely legitimate.

**Comment by lrapetti** [comment]
Closing since we can first fix Travis in `devel` (https://github.com/robotology/human-dynamics-estimation/pull/129), and then proceed with merging `devel` in `master`.

**Pull request closed without merging**
