### PR TITLE
Fix deprecated YARP functions for YARP 3.7 compatibility (feetConstraints/addVectorPublish backport)

### PR DESCRIPTION
**Pull request by traversaro**
I cherry-picked commits from https://github.com/robotology/human-dynamics-estimation/pull/297 and https://github.com/robotology/human-dynamics-estimation/pull/301 on top of this branch to make it compatible with YARP 3.7 .

fyi @lrapetti @diegoferigo @VenusPasandi @Andrea8Testa @valentino-razza @fabiodinatale

### CODE REVIEW

**Comment by traversaro** [comment]
@lrapetti Freel free to merge if you think it is ok.

**Comment by lrapetti** [comment]
> @lrapetti Freel free to merge if you think it is ok.

I noticed the CI is failing, can we merge it anyway?

**Comment by traversaro** [comment]
> > @lrapetti Freel free to merge if you think it is ok.
> 
> I noticed the CI is failing, can we merge it anyway?

Yes, I think the CI is not updated to work correctly. Anyhow, we tested this in the CI of the internal project in which we are consuming this branch.

**Comment by lrapetti** [comment]
> > I noticed the CI is failing, can we merge it anyway?
> 
> Yes, I think the CI is not updated to work correctly. Anyhow, we tested this in the CI of the internal project in which we are consuming this branch.

Fair enough, I'll proceed to merge it then!

**Pull request merged**
