### PR TITLE
Fix windows compilation master

### PR DESCRIPTION
**Pull request by lrapetti**
This PR fixies https://github.com/robotology/human-dynamics-estimation/issues/160#issuecomment-557504971 porting the commit pushed to devel in https://github.com/robotology/human-dynamics-estimation/pull/133/commits/1cf513c765bf82269c097c4174fe4cde903cb486

### CODE REVIEW

**Comment by traversaro** [comment]
In general, I would try to avoid naked new in new code and use stuff like `std::vector` as much as possible to ensure that [RAII](https://en.cppreference.com/w/cpp/language/raii) is used for memory management, and to avoid memory leaks that are difficult to debug or catch. However, as this code is already landed in devel, probably we will need to improve this things in devel.

**Comment by traversaro** [comment]
Beside avoiding naked `new`, it seems that the existing code is lacking `delete` at all, and  so it is creating memory leaks (both here and in `devel`). Probably just having code like: 
~~~
std::vector<double> initEncoderJointPositions;
initEncoderJointPositions.resize(remoteControlBoardJoints);
~~~
is the simplest solution without inserting memory leaks.

**Comment by lrapetti** [comment]
With https://github.com/robotology/human-dynamics-estimation/pull/161/commits/f62538b51dff6d121efcba11c2fe4a5ce87e8625 I am also trying to restore CI for `master`

**Comment by traversaro** [comment]
I just noticed that one of the memory leaks (`double* encoderJointPositions = new double[joints];`) is executed at each cycle of the device, and so it allocates some memory non freed at each cycle, and can **eventually crash the program by memory exhaustion**. Is that device used for demos on the real robot?

**Comment by lrapetti** [comment]
> Is that device used for demos on the real robot?

yes, it has been actually used in the past, not sure if before or after fixing the compilation issue with Windows.

Anyway, thanks for the catch, I will manage to fix it.

**Comment by lrapetti** [comment]
> See comments on memory leak.

fixed with https://github.com/robotology/human-dynamics-estimation/pull/161/commits/04145774d8b6dd6ba9862f9b01d4a309646d984f.

**Pull request merged**
