### PR TITLE
Bug fixing: add vector publishing from IK velocity solution

### PR DESCRIPTION
**Pull request by lrapetti**
Merging into master the fix from @valentino-razza for the missing velocities.

cc @Zweisteine96 @kouroshD

### CODE REVIEW

**Comment by Zweisteine96** [comment]
The bug is related to this issue: https://github.com/ami-iit/element_risk-prediction/issues/64#issuecomment-1095037408

**Comment by kouroshD** [comment]
Please, just check and ensure if the velocities are streamed. Thanks.

**Review by Zweisteine96 — COMMENTED** [review]
Great thx for the help.

**Comment by lrapetti** [comment]
Thanks @Zweisteine96 @kouroshD, merging.

**Pull request merged**
