### PR TITLE
Bump human-dynamics-estimation version to 3.0.0

### LINKED ISSUE #373: Release human-dynamics-estimation v3.0.0
Since https://github.com/robotology/human-dynamics-estimation/pull/372 and https://github.com/robotology/human-dynamics-estimation/pull/367 will break compatibility with previous configurations and dataset, I think we can consider releasing a `v3.0.0` version of the `human-dynamics-estimation` software. What do you think @traversaro? Should we consider instead maintaining the deprecated devices in https://github.com/robotology/human-dynamics-estimation/pull/367?

- [ ] https://github.com/robotology/human-dynamics-estimation/pull/372
- [ ] https://github.com/robotology/human-dynamics-estimation/pull/367

### PR DESCRIPTION
**Pull request by lrapetti**
Closes #373.
Before merging:
- [x] Update documentation with the mapping of the new device names @davidegorbani
- [x] Replace usage of `transformClient` in the configuration files (https://github.com/robotology/wearables/issues/191) @S-Dafarra 
- [x] Replace usage of `controlboardwrapper2` in the configuration files @lrapetti  https://github.com/robotology/human-dynamics-estimation/pull/378

### Changed
- Naming convention from `wrapper`\ `server` to `nws`\ `nwc` (https://github.com/robotology/human-dynamics-estimation/pull/367).
- HumanLogger device to be compatible with the `robot-log-visualizer` (https://github.com/robotology/human-dynamics-estimation/pull/372).

### Added
- Added files for ergoCub teleoperation without using iFeel (https://github.com/robotology/human-dynamics-estimation/pull/374)

### CODE REVIEW

**Review by davidegorbani — APPROVED** [review]
It looks fine to me!

**Comment by S-Dafarra** [comment]
Could you wait for this?  would like to propose changes for using the new ``frameTransformClient`` device

**Comment by lrapetti** [comment]
> Could you wait for this? would like to propose changes for using the new `frameTransformClient` device

Sure! As discussed today, before merging we would also like to improve the documentation on the required changes to use the new `nws`/`nwc` devices. I will update the first comment of this issue

**Comment by davidegorbani** [comment]
I updated the CHANGELOG file as suggested by @traversaro .

**Review by traversaro — APPROVED** [review]

**Comment by S-Dafarra** [comment]
> Could you wait for this? would like to propose changes for using the new `frameTransformClient` device
> 
> I am planning to do this either today or tomorrow

Here the PR: https://github.com/robotology/human-dynamics-estimation/pull/377

**Comment by lrapetti** [comment]
Thanks all, we can merge it

**Pull request merged**
