### PR TITLE
Merge wearables repo in human-dynamics-estimation

### PR DESCRIPTION
**Pull request by traversaro**
As described in https://github.com/robotology/wearables/issues/212 .

The PR history is quite complicated as it contains all the history of wearables, but the relevant commits are actually https://github.com/robotology/human-dynamics-estimation/pull/395/commits/81f4c27e0aef5eab7d6c4edb439f27e2b452fb81 and https://github.com/robotology/human-dynamics-estimation/pull/395/commits/177d7ba39f0efdb03b28a87046edf04f80eb004a, as they are the change to permit the merge.

Almost all the CMake options, CMake installed packages, and python packages should be exactly the same, permitting seamless migration from wearables+human-dynamics-estimation to the "merged" human-dynamics-estimation 4.0.0, the main exception are:

* The Python options `WEARABLES_COMPILE_PYTHON_BINDINGS`, `WEARABLES_DETECT_ACTIVE_PYTHON_SITEPACKAGES`, `WEARABLES_PYTHON_INSTALL_DIR`, `WEARABLES_PYTHON_PIP_METADATA_INSTALL` and `WEARABLES_PYTHON_PIP_METADATA_INSTALLER` are not used, and instead  `HDE_COMPILE_PYTHON_BINDINGS`, `HDE_DETECT_ACTIVE_PYTHON_SITEPACKAGES`, `HDE_PYTHON_INSTALL_DIR`, `HDE_PYTHON_PIP_METADATA_INSTALL` and `HDE_PYTHON_PIP_METADATA_INSTALLER` are used also to enable/disable the installation of the `wearables` python package
* All the `.xml` yarpmanager files are installed in `$CMAKE_INSTALL_PREFIX/share/HumanDynamicsEstimation`, also the one that before were installed in `$CMAKE_INSTALL_PREFIX/share/wearables`, so that only `$CMAKE_INSTALL_PREFIX/share/HumanDynamicsEstimation` needs to be added to `YARP_DATA_DIRS`.

### CODE REVIEW

**Comment by traversaro** [comment]
@S-Dafarra @dariosortino  given that you are the persons that recently merged PRs in hde, you won the co-mantainership of the new repo with me. : )

**Comment by lrapetti** [comment]
:broken_heart:

**Review by dariosortino — APPROVED** [review]

**Comment by dariosortino** [comment]
What should we do after this PR? Uninstall wearables from the current superbuild installation, and update HDE?

**Comment by traversaro** [comment]
> What should we do after this PR? Uninstall wearables from the current superbuild installation, and update HDE?

The only files that is better if they are removed are the one that are installed in `$CMAKE_INSTALL_PREFIX/share/wearables`, everything else should be automatically overwritten by the the new "great" hde.  So you can either uninstall manually, or just delete the whole install directory and let the superbuild reinstall everything.

**Comment by S-Dafarra** [comment]
I wonder whether it is cleaner if we move all the old wearables code in a single sub folder

**Comment by S-Dafarra** [comment]
I see! Actually, I got misled by the structure with which the file modifications are presented in the changes panel in Github. The structured seemed much more flat. By looking at the file structure in the branch directly, it makes more sense.

Long story short, looks good to me.

**Review by S-Dafarra — APPROVED** [review]

**Pull request merged**
