### PR TITLE
Add timeout to wait for data available in interface

### PR DESCRIPTION
**Pull request by lrapetti**
With this PR I am adding a timeout to wait for data being available on the interface. This avoid problems such as https://github.com/robotology/human-dynamics-estimation/issues/356.

Moreover, in https://github.com/robotology/human-dynamics-estimation/commit/7ae0be3fd337b7042c4d82e35640080c90665334 I standardizing the capitalization for the `LogPrefix` variable.

### CODE REVIEW

**Comment by lrapetti** [comment]
@traversaro @GiulioRomualdi @davidegorbani I don't know if this solution make sense to you, or you can propose alternatives? (clearly we might add a parameter that defines the timeout to avoid the device getting stuck waiting)

**Review by traversaro — APPROVED** [review]
As a general comment, it probably make sense to extend the IHumanState interface to also provide this information about the status, as conflating getNumberOfJoints == 0 ==> no first data received may be a bit problematic. Anyhow, as a first fix this is perfect.

**Comment by lrapetti** [comment]
> As a general comment, it probably make sense to extend the IHumanState interface to also provide this information about the status, as conflating getNumberOfJoints == 0 ==> no first data received may be a bit problematic. Anyhow, as a first fix this is perfect.

That make sense, I can open an issue related to this. As usual, a concern is that it would imply that we should update the associated thrift message, and old datasets might no longer be compatible (however, I don't think we are directly using `IHumanState` dumped signal so it should not be a problem).

**Comment by lrapetti** [comment]
> > As a general comment, it probably make sense to extend the IHumanState interface to also provide this information about the status, as conflating getNumberOfJoints == 0 ==> no first data received may be a bit problematic. Anyhow, as a first fix this is perfect.
> 
> That make sense, I can open an issue related to this.

Done https://github.com/robotology/human-dynamics-estimation/issues/360, I'll proceed updating the `CHANGELOG.md` and merging.

**Pull request merged**
