### PR TITLE
Update nws/nwc naming convention

### LINKED ISSUE #359: Change Wrapper/Remapper naming convention to `nws`/`nwc`
Some time ago, in `yarp` the naming convention `nws`/`nwc` was defined (see https://github.com/robotology/yarp/discussions/2441). This was never ported in this repo where we have instead `Wrapper` and `Remapper` devices. 
We might think of moving to this naming convention. 

cc @traversaro

### PR DESCRIPTION
**Pull request by davidegorbani**
This PR closes #359; with this PR the naming convention of the Wrapper and the Remapper is updated to the `nws`/`nwc` now used for the servers and clients in YARP.

### CODE REVIEW

**Comment by lrapetti** [comment]
Great @davidegorbani, I will go trough this PR soon. CI on Windows is failing, but the issue seems to be unrelated to your PR.

Moreover, before merging I would like to fix https://github.com/robotology/human-dynamics-estimation/issues/366 and do a Release, since this PR will break compatibility with old configurations.

**Comment by lrapetti** [comment]
> I rebased the branch on master, I tested on my laptop the HumanStateVisualizer and it is working fine.

Great, however there seems to be a conflict in the files and the commit history seems not to be clean. We can have a look at this together tomorrow!

**Review by lrapetti — COMMENTED** [review]
Thanks for the PR @davidegorbani. A couple of comments:
- can you update the [`CHANGELOG.md`](https://github.com/robotology/human-dynamics-estimation/blob/update_nws_nwc_name/CHANGELOG.md) with the relevant modifications?
- I think we can also change the name of the folders in which those files are currently stored (so removing the `wrappers` and `remappers` folder).

**Comment by davidegorbani** [comment]
> * can you update the [`CHANGELOG.md`](https://github.com/robotology/human-dynamics-estimation/blob/update_nws_nwc_name/CHANGELOG.md) with the relevant modifications?

Yes, sure.




> * think we can also change the name of the folders in which those files are currently stored (so removing the `wrappers` and `remappers` folder).

I was considering changing those names, is it fine `servers` and `clients`?

**Review by lrapetti — COMMENTED** [review]
@davidegorbani can you take care of updating all the configuration files inside [`conf`](https://github.com/robotology/human-dynamics-estimation/tree/update_nws_nwc_name/conf)? Even if you cannot test them, you can simply fins and replace all the names. Eventually we can test together at least those that are actively used for the ergoCub robot teleoperation.

**Comment by davidegorbani** [comment]
Yes, sure!

**Comment by davidegorbani** [comment]
I changed also the name of the namespaces.

**Review by lrapetti — APPROVED** [review]
Thanks @davidegorbani, we can proceed merging!

**Pull request merged**
