### PR TITLE
Bump human-dynamics-estimation version to 2.9.0

### PR DESCRIPTION
**Pull request by lrapetti**
### Fixed
- [`HumanControlBoard`] Fix attach method (https://github.com/robotology/human-dynamics-estimation/pull/365).

### Added
- Added `HumanWrenchWrapper` and `HumanWrenchRemapper` (https://github.com/robotology/human-dynamics-estimation/pull/362/files).
- Added `IHumanWrench` to `HumanLogger` (https://github.com/robotology/human-dynamics-estimation/pull/363).

### CODE REVIEW

**Comment by lrapetti** [comment]
Before doing the new release @davidegorbani can you check https://github.com/robotology/human-dynamics-estimation/issues/366 is fixed when using the updated configuration files?

**Comment by davidegorbani** [comment]
Yes, now it is working correctly! Thank you @lrapetti!

**Comment by lrapetti** [comment]
The CI is failing to setup miniconda on Windows (see https://github.com/robotology/human-dynamics-estimation/actions/runs/6544507226/job/17823261178?pr=368), the error is the following:
```
C:\Windows\system32\cmd.exe /D /S /C "C:\Miniconda\condabin\mamba.bat create --name test "python=3.8""
  Warning: Traceback (most recent call last):
    File "C:\Miniconda\Scripts\mamba-script.py", line 6, in <module>
  
  Traceback (most recent call last):
    File "C:\Miniconda\Scripts\mamba-script.py", line 6, in <module>
  Warning:     from mamba.mamba import main
    File "C:\Miniconda\Lib\site-packages\mamba\mamba.py", line 49, in <module>
  
      from mamba.mamba import main
    File "C:\Miniconda\Lib\site-packages\mamba\mamba.py", line 49, in <module>
  Warning:     import libmambapy as api
    File "C:\Miniconda\Lib\site-packages\libmambapy\__init__.py", line 7, in <module>
  
      import libmambapy as api
    File "C:\Miniconda\Lib\site-packages\libmambapy\__init__.py", line 7, in <module>
  Warning:     raise e
  
      raise e
  Warning:   File "C:\Miniconda\Lib\site-packages\libmambapy\__init__.py", line 4, in <module>
  
    File "C:\Miniconda\Lib\site-packages\libmambapy\__init__.py", line 4, in <module>
  Warning:     from libmambapy.bindings import *  # noqa: F401,F403
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ImportError: DLL load failed while importing bindings: The specified procedure could not be found.
  
      from libmambapy.bindings import *  # noqa: F401,F403
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ImportError: DLL load failed while importing bindings: The specified procedure could not be found.

Error: The process 'C:\Miniconda\condabin\mamba.bat' failed with exit code 1
```

**Comment by lrapetti** [comment]
> The CI is failing to setup miniconda on Windows (see https://github.com/robotology/human-dynamics-estimation/actions/runs/6544507226/job/17823261178?pr=368), the error is the following:
> 
> ```
> C:\Windows\system32\cmd.exe /D /S /C "C:\Miniconda\condabin\mamba.bat create --name test "python=3.8""
>   Warning: Traceback (most recent call last):
>     File "C:\Miniconda\Scripts\mamba-script.py", line 6, in <module>
>   
>   Traceback (most recent call last):
>     File "C:\Miniconda\Scripts\mamba-script.py", line 6, in <module>
>   Warning:     from mamba.mamba import main
>     File "C:\Miniconda\Lib\site-packages\mamba\mamba.py", line 49, in <module>
>   
>       from mamba.mamba import main
>     File "C:\Miniconda\Lib\site-packages\mamba\mamba.py", line 49, in <module>
>   Warning:     import libmambapy as api
>     File "C:\Miniconda\Lib\site-packages\libmambapy\__init__.py", line 7, in <module>
>   
>       import libmambapy as api
>     File "C:\Miniconda\Lib\site-packages\libmambapy\__init__.py", line 7, in <module>
>   Warning:     raise e
>   
>       raise e
>   Warning:   File "C:\Miniconda\Lib\site-packages\libmambapy\__init__.py", line 4, in <module>
>   
>     File "C:\Miniconda\Lib\site-packages\libmambapy\__init__.py", line 4, in <module>
>   Warning:     from libmambapy.bindings import *  # noqa: F401,F403
>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   ImportError: DLL load failed while importing bindings: The specified procedure could not be found.
>   
>       from libmambapy.bindings import *  # noqa: F401,F403
>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   ImportError: DLL load failed while importing bindings: The specified procedure could not be found.
> 
> Error: The process 'C:\Miniconda\condabin\mamba.bat' failed with exit code 1
> ```

Issue opened https://github.com/robotology/human-dynamics-estimation/issues/369

**Review by traversaro — APPROVED** [review]

**Comment by lrapetti** [comment]
Ci was fixed, we can merge it

**Pull request merged**
