### PR TITLE
Use ipopt from homebrew/core

### PR DESCRIPTION
**Pull request by traversaro**
See https://github.com/dartsim/homebrew-dart/issues/76 for a related discussion

### CODE REVIEW

**Comment by lrapetti** [comment]
I see in the test `ipopt` was installed and `HumanStateProvider` was built correctly. The failure is related to something else in the `RobotPositionController` device:

```
Scanning dependencies of target RobotPositionController
[ 56%] Building CXX object devices/RobotPositionController/CMakeFiles/RobotPositionController.dir/yarp_plugin_robot_position_controller.cpp.o
[ 58%] Building CXX object devices/RobotPositionController/CMakeFiles/RobotPositionController.dir/RobotPositionController.cpp.o
/Users/travis/build/robotology/human-dynamics-estimation/devices/RobotPositionController/RobotPositionController.cpp:22:10: fatal error: 'iCub/ctrl/minJerkCtrl.h' file not found
#include <iCub/ctrl/minJerkCtrl.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [devices/RobotPositionController/CMakeFiles/RobotPositionController.dir/RobotPositionController.cpp.o] Error 1
make[1]: *** [devices/RobotPositionController/CMakeFiles/RobotPositionController.dir/all] Error 2
make: *** [all] Error 2
The command "sh .ci/script.sh" exited with 2.
```

**Comment by lrapetti** [comment]
Following the merging of https://github.com/robotology/robotology-superbuild/pull/211, we can procede to merge also this PR.

**Comment by traversaro** [comment]
> The failure is related to something else in the RobotPositionController device:

But there is no failure in the regular `devel` build, right? So it is possible that this failure is related (even in a non-direct way) to the use of the core's ipopt formula.

**Comment by lrapetti** [comment]
> > The failure is related to something else in the RobotPositionController device:
> 
> But there is no failure in the regular `devel` build, right? So it is possible that this failure is related (even in a non-direct way) to the use of the core's ipopt formula.

The last devel failed (see https://github.com/robotology/human-dynamics-estimation/pull/125#issuecomment-500394450) because of `ipopt`, so we never reach the point where we are currently failing (and probably it was already there).

**Comment by traversaro** [comment]
> No, the last devel failed (see #125 (comment)) because of ipopt, so we never reach the point where we are currently failing (and probably it was already there).

Ah ok. So if it is ok for you we can merge this PR as it is.

**Comment by lrapetti** [comment]
> > No, the last devel failed (see #125 (comment)) because of ipopt, so we never reach the point where we are currently failing (and probably it was already there).
> 
> Ah ok. So if it is ok for you we can merge this PR as it is.

yes!

**Pull request merged**
