### PR TITLE
Fix CI in Windows with HumanStateVisualizer

### PR DESCRIPTION
**Pull request by lrapetti**
This PR should fix the failure in Windows CI (https://github.com/robotology/human-dynamics-estimation/runs/1790878536#step:9:10886) as in https://github.com/robotology/idyntree/pull/806.

Moreover, I have enabled the compilation of the `HumanStateVisualizer`

### CODE REVIEW

**Review by S-Dafarra — APPROVED** [review]

**Review by traversaro — APPROVED** [review]

**Review by Yeshasvitvs — APPROVED** [review]
Thanks @lrapetti

**Comment by lrapetti** [comment]
I thought that updating the `vcpkg-robotology` tag would have fixed the compilation since `irrlicht` was recentrly included (https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/pull/39), but it seems to be still failing with 
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
D:/a/human-dynamics-estimation/human-dynamics-estimation/iDynTree/src/visualization/IRRLICHT_INCLUDE_DIR
   used as include directory in directory D:/a/human-dynamics-estimation/human-dynamics-estimation/iDynTree/src/visualization
```

**Comment by traversaro** [comment]
> 
> 
> I thought that updating the `vcpkg-robotology` tag would have fixed the compilation since `irrlicht` was recentrly included ([robotology/robotology-superbuild-dependencies-vcpkg#39](https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/pull/39)), but it seems to be still failing with the error:
> 
> ```
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> D:/a/human-dynamics-estimation/human-dynamics-estimation/iDynTree/src/visualization/IRRLICHT_INCLUDE_DIR
>    used as include directory in directory D:/a/human-dynamics-estimation/human-dynamics-estimation/iDynTree/src/visualization
> ```

I guess you found it, but this was fixed by https://github.com/robotology/idyntree/pull/806 .

**Comment by lrapetti** [comment]
> 
> I guess you found it, but this was fixed by [robotology/idyntree#806](https://github.com/robotology/idyntree/pull/806) .

thanks, yes I have noticed that changes, indeed I tried to change the tag to `devel` and I am waiting to see if that fixes the problem (If I am not wrong, that change has not been included in a release yet).

**Comment by traversaro** [comment]
> 
> 
> > I guess you found it, but this was fixed by [robotology/idyntree#806](https://github.com/robotology/idyntree/pull/806) .
> 
> thanks, yes I have noticed that change, indeed I tried to change the tag to `devel` and I am waiting to see if that fixes the problem (If I am not wrong, that change has not been included in a release yet).

No, it was not included in a release yet, hopefully we should close iDynTree 3 soon.

**Comment by lrapetti** [comment]
All the checks are now passed.

At this stage I think we can use the `devel` branch in CI as long as we don't have the iDyntree release,
what do you think @traversaro ? Would it be better to use directly a commit tag?
Consider that after merging this PR we are planning to do a new release (https://github.com/robotology/human-dynamics-estimation/issues/231).

**Comment by traversaro** [comment]
I think devel is ok.

**Comment by lrapetti** [comment]
> I think devel is ok.

Great! Merging

**Pull request merged**
