### PR TITLE
Add  iCub3 Xsens retargeting to the HDE and fix robot position controller

### PR DESCRIPTION
**Pull request by kouroshD**
This PR adds the following changes:
- Configuration files for retargeting to iCub3 platform
- Correct the colors of iCub2.5 teleoperation model https://github.com/robotology/human-dynamics-estimation/pull/226/commits/909699d1344361fe66bc7a6b635842e491bd2dde
- Update `RobotPositionController` remote control board client https://github.com/robotology/human-dynamics-estimation/pull/224

### CODE REVIEW

**Review by Yeshasvitvs — APPROVED** [review]

**Review by lrapetti — APPROVED** [review]
Looks good to me, but notice that before merging there are some conflicts to be solved.

Also, please consider cleaning the commit history before merging, or squash all the commits.

**Comment by kouroshD** [comment]
> Looks good to me, but notice that before merging there are some conflicts to be solved.

@lrapetti  Which conflict are you indicating? The commit history or another one?!

**Comment by kouroshD** [comment]
> @lrapetti Which conflict are you indicating? The commit history or another one?!

OK, I saw that, they are related to the xml files.

**Comment by kouroshD** [comment]
> Looks good to me, but notice that before merging there are some conflicts to be solved.
Also, please consider cleaning the commit history before merging, or squash all the commits.

Done! I'll wait for CI to complete and then I will merge.

**Pull request merged**
