### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by kouroshD**
related issue on https://github.com/robotology/walking-teleoperation/issues/39

### CODE REVIEW

**Review by lrapetti — APPROVED** [review]
LGTM, @kouroshD can we proceed merging?

**Comment by kouroshD** [comment]
let us check, maybe we change the suggestion for fixing this problem.

**Comment by lrapetti** [comment]
@kouroshD @S-Dafarra I don't know if you agree on this change, and we can merge it.

**Comment by S-Dafarra** [comment]
> @kouroshD @S-Dafarra I don't know if you agree on this change, and we can merge it.

Ok for me!

**Comment by kouroshD** [comment]
Go on with that . Thanks

**Comment by lrapetti** [comment]
Thanks! Merging.

**Pull request merged**
