### PR TITLE
Added conf file for IK using 5 trackers

### PR DESCRIPTION
**Pull request by S-Dafarra**

### CODE REVIEW

**Comment by S-Dafarra** [comment]
I should edit also the other configurations to use ``left_glove`` and ``right_glove``. For this I would need https://github.com/ami-iit/yarp-device-openxrheadset/pull/46 and https://github.com/robotology/walking-teleoperation/pull/151

**Comment by traversaro** [comment]
@S-Dafarra what is the status of this PR?

**Comment by S-Dafarra** [comment]
> @S-Dafarra what is the status of this PR?

I would have liked to do the edits mentioned in the [comment above]( https://github.com/robotology/human-dynamics-estimation/pull/394#issuecomment-2437683183) but it is not blocking in general. What did you have in mind?

**Comment by S-Dafarra** [comment]
> > @S-Dafarra what is the status of this PR?
> 
> I would have liked to do the edits mentioned in the [comment above](https://github.com/robotology/human-dynamics-estimation/pull/394#issuecomment-2437683183) but it is not blocking in general. What did you have in mind?

Done in https://github.com/robotology/human-dynamics-estimation/pull/394/commits/8063532db8d5983579521ab95cd8817d09cf6882

**Comment by traversaro** [comment]
> > @S-Dafarra what is the status of this PR?
> 
> I would have liked to do the edits mentioned in the [comment above](https://github.com/robotology/human-dynamics-estimation/pull/394#issuecomment-2437683183) but it is not blocking in general. What did you have in mind?

I was just wondering if you wanted to include the change in the upcoming release.

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Ok for me, I do not frequently use this configuration files so I may be missing something, if you want feel free to merge!

**Pull request merged**
