### PR TITLE
Merge devel in master

### PR DESCRIPTION
**Pull request by lrapetti**
Following https://github.com/robotology/human-dynamics-estimation/pull/309, we can proceed merging the `devel` branch in `master`, and a new release will follow

### CODE REVIEW

**Comment by traversaro** [comment]
Probably we can merge without review? All the code merge in devel was reviewed when it was merged in devel, and I am not sure anyone can meaningful ~4500 new line of code related to ~110 different commits. 

@lrapetti @RiccardoGrieco

**Review by RiccardoGrieco — APPROVED** [review]
I updated the configuration files used for teleoperation. We can merge after CI checks pass.

**Comment by traversaro** [comment]
> I updated the configuration files used for teleoperation. We can merge after CI checks pass.

CI passed!

**Comment by lrapetti** [comment]
Great, indeed we can proceed merging it!

**Pull request merged**
